#!/bin/zsh

[ ${#} -eq 0 ] && echo "No arguments" && exit 2

build() {
    [ "${1}" = "release" ] && local variant="--release"
    cargo ndk build --target aarch64-linux-android ${variant}
}

push() {
    adb push "./target/aarch64-linux-android/${1}/fseec" "/data/local/tmp"
}

exe() {
    adb shell su -c "/data/local/tmp/fseec" "${@}"
}

case ${1} in
    buildRelease)
        build release
        ;;
    buildDebug)
        build debug
        ;;
    build)
        build release
        build debug
        ;;
    pushRelease)
        build release && push release
        ;;
    pushDebug)
        build debug && push debug
        ;;
    testRelease)
        shift
        build release && push release && exe "${@}"
        ;;
    testDebug)
        shift
        build debug && push debug && exe "${@}"
        ;;
    exe)
        shift
        exe "${@}"
        ;;
    clean)
        cargo clean
        ;;
    *)
        echo "Invalid arguments" && exit 1
esac