#!/bin/zsh

[ ${#} -eq 0 ] && echo "No arguments" && exit 2

build() {
    [ "${1}" = "release" ] && local variant="--release"
    cargo ndk build --target aarch64-linux-android ${variant}
}

case "${1}" in
    buildRelease)
        build release
        ;;
    buildDebug)
        build debug
        ;;
    build)
        build release
        build debug
        ;;
    clean)
        cargo clean
        ;;
    *)
        echo "Invalid arguments" && exit 1
esac