#!/bin/zsh

alias fn='function'

[ ${#} -eq 0 ] && echo "no args" && exit 2

name="fseed"
targetDir="/data/local/tmp"

fn exe() {
  adb shell su -c "${targetDir}/${name}" "${@}"
}

fn build() {
  [ "${1}" = "release" ] && local variant="--release"

  local git_version
  git_version="$(git describe --tags --always 2>/dev/null)" || {
      git_version="0.0.0"
      echo "Failed to get git version, using ${git_version}"
  }
  VERSION_NAME=${git_version} \
  cargo ndk build --target aarch64-linux-android ${variant}
}

fn push() {
  adb push "./target/aarch64-linux-android/${1}/${name}" "${targetDir}"
}

fn main() {
  case "${1}" in
    exe)
      shift
      exe "${@}"
      ;;
    buildRelease)
      build release
      ;;
    buildDebug)
      build debug
      ;;
    buildAll)
      build release
      build debug
      ;;
    pushRelease)
      build release && push release
      ;;
    pushDebug)
      build debug && push debug
      ;;
    testRelease)
      shift
      build release && push release && exe "${@}"
      ;;
    testDebug)
      shift
      build debug && push debug && exe "${@}"
      ;;
    clean)
      cargo clean
      ;;
    *)
      echo "invalid args" && exit 1
  esac
}

main "${@}"