#!/bin/zsh

[ ${#} -eq 0 ] && echo "No arguments" && exit 2

FSEEMODDIR=/data/adb/modules/fs_enhancer_extreme
SRC=src

adb_sudo() {
    adb shell su -c "${@}"
}

wake() {
    adb shell input keyevent KEYCODE_WAKEUP
}

push() {
    local tmp=/data/local/tmp/src
    adb_sudo rm -rf ${tmp} ${FSEEMODDIR}/webroot
    adb push ./${SRC} ${tmp}
    adb_sudo mv -f ${tmp} ${FSEEMODDIR}/webroot
}

stop() {
    local pkgs=(
        "com.dergoogler.mmrl.wx" 
        "io.github.a13e300.ksuwebui"
    )
    for pkg in "${pkgs[@]}"
    do
        adb shell am force-stop ${pkg}
    done
}

debug() {
    push && \
    stop && \
    wake && \
    adb_sudo ${FSEEMODDIR}/bin/fseec startwebui
}

start() {
    push && \
    stop && \
    wake && \
    adb shell am start -n com.dergoogler.mmrl.wx/.ui.activity.MainActivity
}

case ${1} in
    push)
        push
        ;;
    debug)
        debug
        ;;
    start)
        start
        ;;
    *)
        echo "Invalid arguments" && exit 1
esac